# Generated by Django 6.1.1 on 2026-09-26 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_owners', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('balance', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='tenants.tenant')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='wallets.walletowner')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_keys', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'endpoint', 'key'), name='unique_idempotency_key_per_tenant_and_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], max_length=20)),
                ('amount', models.PositiveBigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('idempotency_key', models.CharField(max_length=255)),
                ('related_transfer_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tenants.tenant')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'wallet', '-created_at'], name='wallets_tra_tenant__b8a08e_idx'), models.Index(fields=['tenant', 'idempotency_key'], name='wallets_tra_tenant__221356_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key', 'type'), name='unique_idempotency_key_per_tenant_and_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='walletowner',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref__isnull', False)), fields=('tenant', 'external_ref'), name='unique_owner_external_ref_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
    ]
