# Generated by Django 6.1.1 on 2026-09-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='walletowner',
            options={'ordering': ['-created_at']},
        ),
    ]
